### ISSUE TITLE
[Development Feature] Configure 'Watch Changes' Library For Better Development Experience

### ISSUE THREAD

**Issue by ArkadiK94** [nishaaannnt/advance-bookmarks#10]
# Intro:
Add npm-watch, so every time we make a change in the code we will not need to run `npm run build`. Also, add this change in the CONTRIBUTING.md file. It will make it easier for the developer to make modifications.

What: install npm-watch and add relevant script and configuration

* I would like to pr the changes under the hacktoberfest. What do you think about the need of something like this?

# Expected Behavior:

https://github.com/nishaaannnt/advance-bookmarks/assets/76536506/172de15a-b70e-427c-b914-257b620d0887

https://github.com/nishaaannnt/advance-bookmarks/assets/76536506/e07f2dd0-523f-491b-8aec-bb5cd7925d06

# CONTRIBUTING.md After Changes:
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/76536506/1685223f-1b10-4e6b-8b19-96a51572eaa9)

**Comment by nishaaannnt** [comment]
Hello @ArkadiK94 this is one of the major issue i faced during development and am glad to know their exists a solution to this. 
Please go ahead and make the necessary changes, also pull the latest project.

Thank you
