### ISSUE TITLE
[Bug] When The User Deletes or Adds a bookmark in the browser it doesn't update in the extension.

### ISSUE THREAD

**Issue by ArkadiK94** [nishaaannnt/advance-bookmarks#11]
# Describe the bug
When The User Deletes or Adds a bookmark in the browser it doesn't update in the app extension.

# To Reproduce
Add/Delete a new bookmark
Open the extension

# Expected Behavior
It should be updated automatically

# Screenshot/ Video

https://github.com/nishaaannnt/advance-bookmarks/assets/76536506/539fadb1-66c0-4462-a328-68c066914a8f

* I would like to fix this bug under the hacktoberfest.

**Comment by nishaaannnt** [comment]
go for it @ArkadiK94

**Comment by nishaaannnt** [comment]
hey @ArkadiK94 I thought the code would work fine and merged as it seemed all good but there is an issue that when i open the extension none bookmarks are visible. Please check.

**Comment by ArkadiK94** [comment]
Very strange, it works for me without a problem. Did you create new build in vs code? Did you refresh the extension in chrome://extensions ? Could you send images/short video? Could you click "inspect" from the extension and from service_worker to see if there are errors in the console?

https://github.com/nishaaannnt/advance-bookmarks/assets/76536506/53f18626-8d08-41c7-a037-24c77a14aee0

**Comment by ArkadiK94** [comment]
In addition, for another issue, we need to add a message to user when there was not added any bookmark yet.

**Comment by ArkadiK94** [comment]
@nishaaannnt

**Comment by nishaaannnt** [comment]
@ArkadiK94 Sorry I was a bit busy this week. I will recheck and get back

**Comment by nishaaannnt** [comment]
@ArkadiK94 Hey Sorry, Actually i forgot to refresh the extension in hurry last time. Code works fine everything looks good.

Also can you please raise a PR again as I can just checkout and merge the branch myself but i dont want your hacktober-fest label to be taken away from you. Thank you for your contributions! @ArkadiK94

**Comment by ArkadiK94** [comment]
@nishaaannnt It is ok, I already got enough pr's for the hacktoberfest event. Could you just merge the branch?

**Comment by ArkadiK94** [comment]
@nishaaannnt Pls, tell me if you need me to open a new pr because of the revert, so I will do it :)

**Comment by nishaaannnt** [comment]
@ArkadiK94 hello, yeah man please. 
i ran into some issues and too tired to resolve it lol

**Comment by ArkadiK94** [comment]
@nishaaannnt Hi, it is fine :) I created new pr as the previous one.

**Comment by ArkadiK94** [comment]
@nishaaannnt Hi, I close this issue because I saw that you merged the pr.
