### ISSUE TITLE
Replace loading with a spinner

### ISSUE THREAD

**Issue by lly02** [nishaaannnt/advance-bookmarks#3]
Loading show "fetching..." which is not aesthetically pleasing. I propose changing it to a spinner.
<img width="301" alt="image" src="https://github.com/nishaaannnt/advance-bookmarks/assets/91957823/97b28b88-6b0c-4d8e-890c-721cdf310808">

**Comment by ChaudaryHammad** [comment]
assign it to me i want to work on this issue

**Comment by nishaaannnt** [comment]
Hello @lly02 , currently the time for fetching is in milliseconds so i guess this one is not necessary as we want to keep the extension as light as possible.
If you have any other recommendation please let me know.
Thank you
