### ISSUE TITLE
Custom name for bookmark

### ISSUE THREAD

**Issue by lly02** [nishaaannnt/advance-bookmarks#5]
Allow custom name for bookmark, it doesn't affect the browser's bookmark.

**Comment by lly02** [comment]
@nishaaannnt you can assign all the issues i opened to me

**Comment by nishaaannnt** [comment]
Hello @lly02,  can you please explain about where will you store the changed name? localstorage?

**Comment by lly02** [comment]
That's right

**Comment by nishaaannnt** [comment]
can you please tell me how the name will be changed ? like how the user will interact to change the bookmark name
