### ISSUE TITLE
[Feature]Rearranging the bookmarks with drag and drop 

### ISSUE THREAD

**Issue by nishaaannnt** [nishaaannnt/advance-bookmarks#6]
Currently a fixed list of bookmarks is made available, an option to Drag and Drop to rearrange their sequence can be more convenient.

A bit complex but feel free to ask for any help from my side !

**Comment by Anubhav18200** [comment]
I have resolved the issue kindly check the pull request.
Thanks
@nishaaannnt

**Comment by nishaaannnt** [comment]
hello @Anubhav18200 can you please provide a functioning video for the same ?
thank you

**Comment by Anubhav18200** [comment]
you can check forked repo 
https://github.com/Anubhav18200/advance-bookmarks/tree/add-feature/drag-drop
Clone it and check the working . I have checked it from my side its working .
@nishaaannnt 

In this image the c++ is at first 
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/61912902/0a2fa26e-6346-4792-97ea-2700db3b8037)

Now i will drag and drop its position
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/61912902/1d9ecefd-82be-46f8-9b4b-8a5b8b1f4727)

**Comment by nishaaannnt** [comment]
i saw the code and found issues in it such as 

1. I can't access the bookmark just by clicking on it (maybe just add a option to drag from far right to avoid any issue)
2. the length of the name is overflowing which i had set to max 30 characters or so.

please look into the above issues

thank you!
also dont forget to leave a star ;)

**Comment by Anubhav18200** [comment]
@nishaaannnt 
sorry for the issues
i have resolved the above 2 issues. Now you can check and confirm.
I have created a new pull request.

Thank you. 

Added the 3dot icon for drag-drop functionality.
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/61912902/0f1f018a-9ce9-4615-a6b3-12df8ce54e27)

**Comment by nishaaannnt** [comment]
Thank you @Anubhav18200 !
