### ISSUE TITLE
[Feature] Toggle between dark and light mode

### ISSUE THREAD

**Issue by nishaaannnt** [nishaaannnt/advance-bookmarks#7]
A button in info section of extension to toggle between light and dark mode for extension.

**Comment by tara-matthew** [comment]
Hey, could I work on this please?

**Comment by nishaaannnt** [comment]
go for it @tara-matthew. but please make a new branch and then raise a PR. 
Start working on it .

**Comment by GD0910** [comment]
@nishaaannnt can i work on this feature as well

**Comment by nishaaannnt** [comment]
@GD0910 i will wait till tomorrow for the PR. If none occurs i will assign the issue to you

**Comment by GD0910** [comment]
hi @nishaaannnt can i work on this feature now ?

**Comment by nishaaannnt** [comment]
@GD0910 please fork and make a new branch and make necessary changes. 
Thank you

**Comment by GD0910** [comment]
Hi @nishaaannnt I have implemented dark mode toggle function 
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/0b92993d-cdb8-4746-b1cd-470743b08dba)

![image](https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/62f8c03d-3071-4377-9b1b-83fd4a31dcca)
and This is how it looks in light mode 
if any changes to be made please infom me the necessary changes and i wll try to complete that issue

This is my first contribution in open source .Your suggestions would be valuable

**Comment by nishaaannnt** [comment]
@GD0910 can you show me both dark and light mode images?

**Comment by GD0910** [comment]
> @GD0910 can you show me both dark and light mode images?

sure

**Comment by GD0910** [comment]
extra : I changed 3-dot icon as  in previous icon there wasn't spacing between the dots

https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/a2181089-ae79-4d5a-b5c8-538d657a84a1

**Comment by nishaaannnt** [comment]
@GD0910 recommendations -

1. Add the toggle button in about page . maybe on the right side of buy me a coffee.
2. The dark mode color seems to be changed then the standard dark theme of extension. please keep the same default dark color theme.

Rest looks good to me.
If you can do above changes let me know.
Thank you

**Comment by GD0910** [comment]
> @GD0910 recommendations -
> 
> 1. Add the toggle button in about page . maybe on the right side of buy me a coffee.
> 2. The dark mode color seems to be changed then the standard dark theme of extension. please keep the same default dark color theme.
> 
> Rest looks good to me. If you can do above changes let me know. Thank you

i will reset the dark mode color theme 
About the toggle button : It will be better if we place it in main page rather than in about section as it will be easy to use and not everyone will open the about section

**Comment by GD0910** [comment]
![image](https://github.com/nishaaannnt/advance-bookmarks/assets/88530462/40b04b06-06d5-4c9e-a5a8-33344e65ea9f)
I have switched to the original colors for dark theme
